// apps/web-next/app/[locale]/(site)/login/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import Image from 'next/image';
import { useTranslations } from 'next-intl';
import { useAuth } from '@/hooks/useAuth';

export default function LoginPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const t = useTranslations('auth.login');
  const commonT = useTranslations('common');
  const { login } = useAuth();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [sessionExpired, setSessionExpired] = useState(false);

  useEffect(() => {
    if (searchParams.get('expired') === 'true') {
      setSessionExpired(true);
    }
  }, [searchParams]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      await login(email, password);
      router.push('/dashboard');
    } catch (err: any) {
      setError(err.message || t('errors.generic'));
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-cyan-50 dark:from-slate-950 dark:via-slate-900 dark:to-slate-950">
      <div className="mx-auto max-w-7xl px-4 md:px-6 lg:px-8 py-12 lg:py-20">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          {/* Left Column - Form */}
          <div className="order-2 lg:order-1">
            <div className="max-w-md">
            

              {/* Header */}
              <div className="mb-8">
                <h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 dark:text-slate-100 mb-3">{t('title')}</h1>
                <p className="text-lg text-slate-600 dark:text-slate-300">{t('subtitle')}</p>
              </div>

              {/* Session Expired Message */}
              {sessionExpired && !error && (
                <div className="mb-6 p-4 rounded-2xl bg-amber-50 dark:bg-amber-950/50 border-2 border-amber-200 dark:border-amber-800 text-amber-800 dark:text-amber-300">
                  <div className="flex items-center gap-3">
                    <svg className="w-5 h-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <span className="font-medium text-sm">{t('sessionExpired')}</span>
                  </div>
                </div>
              )}

              {/* Error Message */}
              {error && (
                <div className="mb-6 p-4 rounded-2xl bg-red-50 dark:bg-red-950/50 border-2 border-red-200 dark:border-red-800 text-red-700 dark:text-red-300">
                  <div className="flex items-center gap-3">
                    <svg className="w-5 h-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <span className="font-medium text-sm">{error}</span>
                  </div>
                </div>
              )}

              {/* Form */}
              <form onSubmit={handleSubmit} className="space-y-5">
                <div>
                  <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">{t('form.emailLabel')}</label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                      <svg className="w-5 h-5 text-slate-400 dark:text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                      </svg>
                    </div>
                    <input
                      type="email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      className="w-full pl-12 pr-4 py-3.5 rounded-xl border-2 border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
                      placeholder={t('form.emailPlaceholder')}
                      required
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">{t('form.passwordLabel')}</label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                      <svg className="w-5 h-5 text-slate-400 dark:text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                      </svg>
                    </div>
                    <input
                      type={showPassword ? 'text' : 'password'}
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      className="w-full pl-12 pr-12 py-3.5 rounded-xl border-2 border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
                      placeholder={t('form.passwordPlaceholder')}
                      required
                    />
                    <button
                      type="button"
                      onClick={() => setShowPassword(!showPassword)}
                      className="absolute inset-y-0 right-0 pr-4 flex items-center text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-300"
                    >
                      {showPassword ? (
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
                        </svg>
                      ) : (
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                        </svg>
                      )}
                    </button>
                  </div>
                </div>

                <button
                  type="submit"
                  disabled={loading}
                  className="w-full py-4 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-600 text-white font-bold text-lg hover:from-blue-700 hover:to-cyan-700 transition-all shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed transform hover:-translate-y-0.5"
                >
                  {loading ? (
                    <span className="flex items-center justify-center gap-2">
                      <div className="inline-block animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent"></div>
                      {t('buttons.signingIn')}
                    </span>
                  ) : (
                    <span className="flex items-center justify-center gap-2">
                      {t('buttons.signIn')}
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                      </svg>
                    </span>
                  )}
                </button>
              </form>

              {/* Footer Links */}
              <div className="mt-8 text-center">
                <p className="text-slate-600 dark:text-slate-300">
                  {t('footer.prompt')}{' '}
                  <Link href="/signup" className="text-blue-700 dark:text-blue-400 font-bold hover:text-blue-800 dark:hover:text-blue-300 transition-colors">
                    {t('footer.link')}
                  </Link>
                </p>
              </div>
            </div>
          </div>

          {/* Right Column - Image & Info */}
          <div className="order-1 lg:order-2">
            <div className="relative">
              <div className="relative rounded-3xl overflow-hidden shadow-2xl">
                <Image
                  src="https://images.unsplash.com/photo-1606811971618-4486d14f3f99?q=80&w=1200&auto=format&fit=crop"
                  alt="Qadri's Clinic - Professional Dental Care"
                  width={1200}
                  height={800}
                  sizes="(max-width: 1024px) 100vw, 50vw"
                  className="h-full w-full object-cover"
                  priority
                />
                <div className="absolute inset-0 bg-gradient-to-t from-slate-900/80 via-slate-900/20 to-transparent"></div>

                {/* Overlay Content */}
                <div className="absolute bottom-0 left-0 right-0 p-8 text-white">
                  <h2 className="text-3xl font-bold mb-3">{t('hero.title')}</h2>
                  <p className="text-blue-100 text-lg mb-6">{t('hero.subtitle')}</p>

                  {/* Features */}
                  <div className="grid grid-cols-2 gap-4">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-lg bg-white/20 backdrop-blur-sm flex items-center justify-center flex-shrink-0">
                        <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                      </div>
                      <span className="text-sm font-semibold">{t('hero.features.experts')}</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-lg bg-white/20 backdrop-blur-sm flex items-center justify-center flex-shrink-0">
                        <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                      </div>
                      <span className="text-sm font-semibold">{t('hero.features.support')}</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Floating Stats Card */}
              <div className="hidden lg:block absolute -left-12 top-1/2 -translate-y-1/2">
                <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 shadow-2xl border border-slate-100 dark:border-slate-700 w-48">
                  <div className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-cyan-600 dark:from-blue-400 dark:to-cyan-400 mb-2">{t('hero.stat.value')}</div>
                  <div className="text-sm font-semibold text-slate-600 dark:text-slate-300">{t('hero.stat.label')}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}

// apps/admin-nuxt/pages/login.vue
<template>
  <div class="flex min-h-screen bg-white dark:bg-gray-900 transition-colors">
    <!-- Left Panel - Branding -->
    <div class="hidden w-1/2 bg-primary-gradient lg:flex lg:flex-col lg:justify-between p-12">
      <div>
          <div class="flex items-center gap-3">
            <div class="flex h-12 w-12 items-center justify-center rounded-xl bg-white shadow-md shadow-slate-900/10">
              <img
                src="https://imagedelivery.net/K88oXEK4nwOFUDLZaSq1vg/6c79054b-5ecc-4a97-be03-441518f70200/public"
                alt="Clinic logo"
                class="h-8 w-8"
                loading="lazy"
              />
            </div>
            <div class="text-white">
              <p class="text-sm font-medium opacity-90">{{ t('auth.login.branding.welcome') }}</p>
              <p class="text-xl font-bold">{{ t('auth.login.branding.title') }}</p>
            </div>
          </div>
      </div>
      
      <div class="space-y-8">
        <div class="space-y-4">
          <h1 class="text-4xl font-bold leading-tight text-white">
            {{ t('auth.login.branding.headlineLine1') }}<br />{{ t('auth.login.branding.headlineLine2') }}
          </h1>
          <p class="text-lg text-violet-100">
            {{ t('auth.login.branding.description') }}
          </p>
        </div>

        <!-- Hero Mockup -->
        <div class="relative rounded-4xl overflow-hidden border border-white/60 shadow-2xl shadow-slate-900/40 bg-gradient-to-br from-white/10 via-white/5 to-white/0 backdrop-blur-xl p-4">
          <div class="absolute inset-0 pointer-events-none bg-[radial-gradient(circle_at_20%_20%,rgba(255,255,255,0.18),transparent_35%),radial-gradient(circle_at_80%_0%,rgba(59,130,246,0.2),transparent_25%),radial-gradient(circle_at_20%_80%,rgba(94,234,212,0.18),transparent_30%)]"></div>
          <div class="relative rounded-3xl overflow-hidden ring-1 ring-white/20">
            <img
              src="https://imagedelivery.net/K88oXEK4nwOFUDLZaSq1vg/11137b81-cbbd-4b24-daac-4b1ea5499a00/public?auto=format&fit=crop&w=1800&q=80"
              alt="Dashboard preview"
              class="w-full h-full object-cover"
              loading="lazy"
            />
            <div class="absolute inset-0 bg-gradient-to-t from-slate-900/65 via-slate-900/35 to-transparent"></div>
            <div class="absolute bottom-0 left-0 right-0 p-6 space-y-3 text-white">
              <div class="flex items-center gap-2 text-xs font-semibold tracking-wide uppercase text-blue-100">
                <span class="h-2 w-2 rounded-full bg-emerald-400 animate-pulse"></span>
                {{ t('auth.login.branding.tagline') }}
              </div>
              <p class="text-2xl font-bold leading-tight">Data-rich overview, crafted for clinic teams.</p>
              <div class="grid grid-cols-3 gap-3 text-sm">
                <div class="rounded-2xl bg-white/10 px-3 py-2">
                  <p class="text-blue-100 text-xs">{{ t('auth.login.branding.metrics.sessions') }}</p>
                  <p class="text-lg font-semibold">+18%</p>
                </div>
                <div class="rounded-2xl bg-white/10 px-3 py-2">
                  <p class="text-blue-100 text-xs">{{ t('auth.login.branding.metrics.waitTime') }}</p>
                  <p class="text-lg font-semibold">12m</p>
                </div>
                <div class="rounded-2xl bg-white/10 px-3 py-2">
                  <p class="text-blue-100 text-xs">{{ t('auth.login.branding.metrics.satisfaction') }}</p>
                  <p class="text-lg font-semibold">4.8★</p>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
      
      <div class="flex items-center gap-4 text-sm text-violet-200">
        <a href="#" class="hover:text-white transition-colors">{{ t('auth.login.branding.links.privacy') }}</a>
        <span>•</span>
        <a href="#" class="hover:text-white transition-colors">{{ t('auth.login.branding.links.terms') }}</a>
        <span>•</span>
        <a href="#" class="hover:text-white transition-colors">{{ t('auth.login.branding.links.support') }}</a>
      </div>
    </div>
    
    <!-- Right Panel - Login Form -->
    <div class="flex w-full items-center justify-center bg-gradient-to-br from-slate-50 to-slate-100 dark:from-gray-800 dark:to-gray-900 p-8 lg:w-1/2 relative">
      <!-- Theme Toggle Button -->
      <div class="absolute top-4 right-4">
        <UButton
          :icon="colorMode.value === 'dark' ? 'i-lucide-sun' : 'i-lucide-moon'"
          color="gray"
          variant="ghost"
          size="lg"
          @click="toggleColorMode"
          class="rounded-full"
        />
      </div>

      <div class="w-full max-w-md space-y-8">
        <!-- Mobile Header -->
        <div class="text-center lg:hidden">
          <div class="mx-auto flex h-14 w-14 items-center justify-center rounded-xl bg-white shadow-lg shadow-violet-500/30">
            <img
              src="https://imagedelivery.net/K88oXEK4nwOFUDLZaSq1vg/6c79054b-5ecc-4a97-be03-441518f70200/public"
              alt="Clinic logo"
              class="h-9 w-9"
              loading="lazy"
            />
          </div>
          <h1 class="mt-4 text-2xl font-bold text-gray-900 dark:text-white">{{ t('auth.login.mobileHeader.title') }}</h1>
          <p class="mt-2 text-sm text-slate-600 dark:text-gray-400">{{ t('auth.login.mobileHeader.subtitle') }}</p>
        </div>

        <div class="rounded-xl border border-slate-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-8 shadow-lg">
          <div class="space-y-6">
            <div class="hidden lg:block">
              <h2 class="text-2xl font-bold text-gray-900 dark:text-white">{{ t('auth.login.form.title') }}</h2>
              <p class="mt-2 text-sm text-slate-600 dark:text-gray-400">
                {{ t('auth.login.form.subtitle') }}
              </p>
            </div>

            <UAlert
              v-if="errorMessage !== null"
              color="red"
              variant="soft"
              icon="i-lucide-alert-circle"
              :title="errorMessage"
              class="animate-shake"
            />

            <form @submit.prevent="onSubmit" class="space-y-5">
              <UFormGroup
                :label="t('auth.login.form.tenantLabel')"
                :hint="t('auth.login.form.tenantHint')"
                name="tenant"
                required
              >
                <div class="relative">
                  <input
                    id="tenant-input"
                    name="tenant"
                    type="text"
                    autocomplete="off"
                    :placeholder="t('auth.login.form.tenantPlaceholder')"
                    class="block w-full transition-all duration-200 border border-slate-300 dark:border-gray-600 focus:border-primary-500 dark:focus:border-primary-400 placeholder:text-slate-400 dark:placeholder:text-gray-500 disabled:bg-slate-50 dark:disabled:bg-gray-800 disabled:cursor-not-allowed form-input rounded-lg h-11 text-base py-2.5 shadow-sm bg-white dark:bg-gray-700 text-gray-900 dark:text-white ring-1 ring-inset ring-gray-300 dark:ring-gray-600 focus:ring-2 focus:ring-primary-500 dark:focus:ring-primary-400 pl-16 pr-3.5"
                    v-model="loginTenantSlug"
                  />
                  <span class="absolute inset-y-0 start-0 flex items-center pointer-events-none px-3.5 rounded-s-lg bg-primary-gradient-soft">
                    <span class="flex h-8 w-8 items-center justify-center rounded-full bg-white/90 dark:bg-gray-800/90 shadow-inner">
                      <UIcon name="i-lucide-building" class="h-4 w-4 text-primary-600 dark:text-primary-300" aria-hidden="true" />
                    </span>
                  </span>
                </div>
              </UFormGroup>

              <UFormGroup :label="t('auth.login.form.emailLabel')" name="email" required>
                <div class="relative">
                  <input
                    id="email-input"
                    name="email"
                    type="email"
                    autocomplete="username"
                    :placeholder="t('auth.login.form.emailPlaceholder', { at: '@' })"
                    class="block w-full transition-all duration-200 border border-slate-300 dark:border-gray-600 focus:border-primary-500 dark:focus:border-primary-400 placeholder:text-slate-400 dark:placeholder:text-gray-500 disabled:bg-slate-50 dark:disabled:bg-gray-800 disabled:cursor-not-allowed form-input rounded-lg h-11 text-base py-2.5 shadow-sm bg-white dark:bg-gray-700 text-gray-900 dark:text-white ring-1 ring-inset ring-gray-300 dark:ring-gray-600 focus:ring-2 focus:ring-primary-500 dark:focus:ring-primary-400 pl-16 pr-3.5"
                    v-model="form.email"
                  />
                  <span class="absolute inset-y-0 start-0 flex items-center pointer-events-none px-3.5 rounded-s-lg bg-primary-gradient-soft">
                    <span class="flex h-8 w-8 items-center justify-center rounded-full bg-white/90 dark:bg-gray-800/90 shadow-inner">
                      <UIcon name="i-lucide-mail" class="h-4 w-4 text-primary-600 dark:text-primary-300" aria-hidden="true" />
                    </span>
                  </span>
                </div>
              </UFormGroup>

              <UFormGroup :label="t('auth.login.form.passwordLabel')" name="password" required>
              <div class="relative">
                <input
                  id="password-input"
                  name="password"
                  :type="showPassword ? 'text' : 'password'"
                  autocomplete="current-password"
                  :placeholder="t('auth.login.form.passwordPlaceholder')"
                  class="block w-full transition-all duration-200 border border-slate-300 dark:border-gray-600 focus:border-primary-500 dark:focus:border-primary-400 placeholder:text-slate-400 dark:placeholder:text-gray-500 disabled:bg-slate-50 dark:disabled:bg-gray-800 disabled:cursor-not-allowed form-input rounded-lg h-11 text-base py-2.5 shadow-sm bg-white dark:bg-gray-700 text-gray-900 dark:text-white ring-1 ring-inset ring-gray-300 dark:ring-gray-600 focus:ring-2 focus:ring-primary-500 dark:focus:ring-primary-400 pl-16 pr-3.5"
                  v-model="form.password"
                />
                <span class="absolute inset-y-0 start-0 flex items-center pointer-events-none px-3.5 rounded-s-lg bg-primary-gradient-soft">
                  <span class="flex h-8 w-8 items-center justify-center rounded-full bg-white/90 dark:bg-gray-800/90 shadow-inner">
                    <UIcon name="i-lucide-lock" class="h-4 w-4 text-primary-600 dark:text-primary-300" aria-hidden="true" />
                  </span>
                </span>
                <UButton
                  type="button"
                  variant="ghost"
                  size="xs"
                  class="absolute inset-y-1 end-2 flex items-center"
                  @click.prevent="showPassword = !showPassword"
                >
                  <span
                    class="iconify flex-shrink-0 h-4 w-4"
                    :class="showPassword ? 'i-lucide:eye-off' : 'i-lucide:eye'"
                    aria-hidden="true"
                  ></span>
                </UButton>
              </div>
              </UFormGroup>

              <div class="flex items-center justify-between text-sm">
                <label class="flex items-center gap-2 cursor-pointer">
                  <input type="checkbox" class="rounded border-slate-300 dark:border-gray-600 text-primary-600 dark:text-primary-400 focus:ring-primary-500 dark:focus:ring-primary-400 dark:bg-gray-700" />
                  <span class="text-slate-700 dark:text-gray-300">{{ t('auth.login.rememberMe') }}</span>
                </label>
                <NuxtLink to="/forgot-password" class="font-medium text-primary-600 dark:text-primary-300 hover:text-primary-700 dark:hover:text-primary-200 transition-colors">
                  {{ t('auth.login.forgotPassword') }}
                </NuxtLink>
              </div>

              <UButton
                :loading="pending"
                type="submit"
                color="violet"
                size="lg"
                block
                class="justify-center shadow-md hover:shadow-lg"
              >
                <template #leading>
                  <UIcon name="i-lucide-log-in" class="h-5 w-5" />
                </template>
                {{ t('auth.login.submit') }}
              </UButton>
            </form>
          </div>
        </div>

        <p class="text-center text-sm text-slate-600 dark:text-gray-400">
          {{ t('auth.login.needAccess.text') }}
          <a href="#" class="font-medium text-primary-600 dark:text-primary-300 hover:text-primary-700 dark:hover:text-primary-200 transition-colors">
            {{ t('auth.login.needAccess.cta') }}
          </a>
        </p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { StaffLoginRequest } from "@/types/auth";

definePageMeta({
  layout: false
});

const { t } = useI18n();
const auth = useAuth();
const router = useRouter();
const route = useRoute();
const colorMode = useColorMode();
const { tenantSlug, setTenantSlug } = useTenantSlug();
const loginTenantSlug = ref<string>(tenantSlug.value);

const tenantFromQuery = computed(() => {
  const value = Array.isArray(route.query.tenant)
    ? route.query.tenant[0]
    : route.query.tenant;
  return typeof value === "string" ? value.trim().toLowerCase() : "";
});

const applyTenantFromQuery = (slug: string) => {
  if (!slug) return;
  setTenantSlug(slug);
  if (import.meta.client) {
    const cleanedQuery = { ...route.query };
    delete cleanedQuery.tenant;
    router.replace({ path: route.path, query: cleanedQuery }).catch(() => {});
  }
};

if (tenantFromQuery.value) {
  applyTenantFromQuery(tenantFromQuery.value);
}

watch(tenantFromQuery, (slug) => {
  if (slug) {
    applyTenantFromQuery(slug);
  }
});

watch(
  () => tenantSlug.value,
  (slug) => {
    if (slug && slug !== loginTenantSlug.value) {
      loginTenantSlug.value = slug;
    }
  },
  { immediate: true }
);

watch(loginTenantSlug, (slug) => {
  if (slug) {
    setTenantSlug(slug);
  }
});

const form = reactive<StaffLoginRequest>({
  email: "",
  password: "",
  twoFactorCode: ""
});

const pending = ref(false);
const errorMessage = ref<string | null>(null);
const showPassword = ref(false);

const onSubmit = async (event?: Event) => {
  console.log('[Login] Form submitted', form);

  if (event) {
    event.preventDefault();
  }

  pending.value = true;
  errorMessage.value = null;

  try {
    console.log('[Login] Calling auth.login with:', form);
    const payload: StaffLoginRequest = {
      email: form.email,
      password: form.password,
      twoFactorCode: form.twoFactorCode?.trim() ? form.twoFactorCode.trim() : undefined
    };
    await auth.login(payload);
    console.log('[Login] Login successful, redirecting...');

    const redirect = Array.isArray(route.query.redirect)
      ? route.query.redirect[0]
      : route.query.redirect;
    await router.push(redirect && redirect !== "/login" ? redirect : "/");
  } catch (error) {
    console.error('[Login] Login failed:', error);
    errorMessage.value = (error as Error).message;
  } finally {
    pending.value = false;
  }
};

const onTwoFactorInput = (event: Event) => {
  const input = event.target as HTMLInputElement;
  const sanitized = input.value.replace(/\D/g, "").slice(0, 6);
  form.twoFactorCode = sanitized;
  input.value = sanitized;
};

const toggleColorMode = () => {
  colorMode.preference = colorMode.value === 'dark' ? 'light' : 'dark';
};
</script>

<style scoped>
@keyframes shake {
  0%, 100% { transform: translateX(0); }
  25% { transform: translateX(-5px); }
  75% { transform: translateX(5px); }
}

.animate-shake {
  animation: shake 0.4s ease-in-out;
}
</style>
